services:
  - type: web
    name: souta-portal
    runtime: static
    buildCommand: ""
    staticPublishPath: ./
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=300
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
